export type Language = 'en' | 'zh'

export const messages = {
  en: {
    workspace: 'Course booking workspace',
    loginTitle: 'Put every lesson in the right place.',
    signupTitle: 'Create your EduBook account.',
    intro: 'Meet the right teacher, across any timezone.',
    name: 'Your name', email: 'Email', password: 'Password', role: 'I am a', student: 'Student', teacher: 'Teacher', timezone: 'Your timezone',
    detectedTimezone: 'Detected timezone — you can change it', login: 'Sign in to EduBook →', signup: 'Create account →', processing: 'Working…',
    noAccount: 'New to EduBook? Create an account', hasAccount: 'Already have an account? Sign in',
    connected: 'Live Supabase connection', booking: 'Book a lesson', myBookings: 'My bookings', manage: 'Manage bookings', schedule: 'Schedule settings', signOut: 'Sign out',
    findLesson: 'Find the right lesson', featured: 'Featured teachers', choose: 'Choose a time that works for you', calendar: 'Availability', shownIn: 'Shown in your timezone',
    bookingConfirm: 'Booking request', pending: 'Pending confirmation', selectTime: 'Select a time to continue', teacherTime: 'Teacher local time', yourTime: 'Your time', submit: 'Submit request →', submitting: 'Submitting…',
    noTeachers: 'No teachers have joined yet', noSlots: 'No available times in this window', noBookings: 'No bookings yet', retry: 'Try again',
    teacherDesk: 'Teacher workspace', applications: 'Booking requests', pendingCount: 'pending requests', confirm: 'Confirm', reject: 'Reject', cancel: 'Cancel',
    fixedTimes: 'Weekly availability', lessonSettings: 'Lesson settings', minutes: 'Minutes per lesson', blocked: 'Blocked periods', add: 'Add', remove: 'Remove', save: 'Save',
    language: '中文', setupMissing: 'Supabase is not configured for this deployment yet.', otp: 'Email verification code', otpHint: 'Enter the code sent to your email.', sendCode: 'Send verification code →', verifyCode: 'Verify and continue →', changeEmail: 'Use a different email', forgotPassword: 'Forgot your password?', forgotTitle: 'Reset your password.', resetTitle: 'Choose a new password.', resetCode: 'Reset code', signupCode: 'Email verification code', signupHint: 'Enter the 6-digit code sent to your email. Your email is locked until verification finishes.', newPassword: 'New password', sendSignupCode: 'Send verification code →', resendCode: 'Resend code', verifySignup: 'Verify email and create account →', sendResetCode: 'Send reset code →', resetPassword: 'Set new password →', backToLogin: 'Back to sign in', resetHint: 'We will send a one-time code to your email.', authInvalid: 'The email or password is incorrect.', authExpired: 'That code has expired. Request a new code and enter the latest one.', authNotConfirmed: 'Please confirm your email before signing in.', authAlreadyRegistered: 'An account with this email already exists.', authRateLimited: 'Too many attempts. Please wait a moment and try again.', authGeneric: 'Authentication failed. Please try again.',
  },
  zh: {
    workspace: '课程预约工作台', loginTitle: '把每一次学习，安排在合适的时间。', signupTitle: '创建你的 EduBook 账户。', intro: '跨越时区，也能和合适的老师从容见面。',
    name: '你的称呼', email: '邮箱', password: '密码', role: '你的身份', student: '学生', teacher: '老师', timezone: '你的时区', detectedTimezone: '已自动识别时区，可修改', login: '登录 EduBook →', signup: '创建账户 →', processing: '处理中…', noAccount: '还没有账户？创建一个', hasAccount: '已有账户？返回登录', connected: 'Supabase 实时连接', booking: '预约课程', myBookings: '预约记录', manage: '预约管理', schedule: '排期设置', signOut: '退出', findLesson: '找到适合你的课堂', featured: '精选老师', choose: '选择一个适合你的时间', calendar: '可预约时间', shownIn: '按你的时区显示', bookingConfirm: '预约确认', pending: '待确认', selectTime: '选择时间后继续', teacherTime: '老师当地时间', yourTime: '你的时间', submit: '提交预约申请 →', submitting: '提交中…', noTeachers: '还没有老师入驻', noSlots: '这段时间暂无可预约时段', noBookings: '还没有预约记录', retry: '重试', teacherDesk: '老师工作台', applications: '预约申请', pendingCount: '条待处理', confirm: '确认', reject: '拒绝', cancel: '取消', fixedTimes: '固定授课时间', lessonSettings: '课程设置', minutes: '每节课分钟数', blocked: '不可预约时段', add: '添加', remove: '移除', save: '保存', language: 'EN', setupMissing: '当前部署尚未配置 Supabase。', otp: '邮箱验证码', otpHint: '请输入发送到邮箱的验证码。', sendCode: '发送验证码 →', verifyCode: '验证并继续 →', changeEmail: '更换邮箱', forgotPassword: '忘记密码？', forgotTitle: '重置你的密码。', resetTitle: '设置新密码。', resetCode: '重置验证码', signupCode: '邮箱验证码', signupHint: '请输入发送到邮箱的 6 位验证码。验证完成前邮箱不可修改。', newPassword: '新密码', sendSignupCode: '发送验证码 →', resendCode: '重新发送验证码', verifySignup: '验证邮箱并创建账户 →', sendResetCode: '发送重置验证码 →', resetPassword: '设置新密码 →', backToLogin: '返回登录', resetHint: '我们会向你的邮箱发送一次性验证码。', authInvalid: '邮箱或密码不正确。', authExpired: '验证码已过期，请重新发送并使用最新验证码。', authNotConfirmed: '请先完成邮箱确认，再登录。', authAlreadyRegistered: '该邮箱已经注册过账户。', authRateLimited: '尝试次数过多，请稍后再试。', authGeneric: '认证失败，请稍后再试。',
  },
} as const
