<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { supabase, supabaseConfigured } from './lib/supabase'
import { formatViewerTime, generateSlots, type BookingSlot } from './lib/booking'
import type { Availability, BlockedPeriod, Booking, BusySlot, Profile, Role } from './lib/types'
import { messages, type Language } from './lib/i18n'

const language = ref<Language>((localStorage.getItem('edubook-language') as Language) || 'en')
const copy = computed(() => messages[language.value])
const detectedTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'
const timezoneOptions = Array.from(new Set([detectedTimezone, 'UTC', 'Asia/Shanghai', 'Asia/Tokyo', 'Europe/London', 'America/New_York', 'America/Los_Angeles', 'Australia/Sydney']))
const session = ref<{ user: { id: string } } | null>(null)
const profile = ref<Profile | null>(null)
const auth = ref({ username: '', password: '' })
const adminForm = ref({ username: '', password: '', displayName: '', role: 'STUDENT' as Role, timezone: detectedTimezone })
const teachers = ref<Profile[]>([]); const users = ref<Profile[]>([]); const bookings = ref<Booking[]>([])
const availability = ref<Availability[]>([]); const blocked = ref<BlockedPeriod[]>([]); const busySlots = ref<BusySlot[]>([])
const selectedTeacherId = ref(''); const selectedSlot = ref<BookingSlot | null>(null); const weekStart = ref(new Date())
const activeNav = ref('book'); const loading = ref(false); const busy = ref(false); const errorMessage = ref(''); const toast = ref('')
const newRule = ref({ weekday: 1, start: '09:00', end: '12:00' }); const blockedForm = ref({ start: '', end: '', reason: '' })
const viewerTimezone = computed(() => profile.value?.timezone || detectedTimezone)
const currentTeacher = computed(() => teachers.value.find(x => x.id === selectedTeacherId.value) || teachers.value[0])
const studentBookings = computed(() => bookings.value.filter(x => x.student_id === profile.value?.id))
const teacherBookings = computed(() => bookings.value.filter(x => x.teacher_id === profile.value?.id))
const slots = computed(() => {
  if (!currentTeacher.value) return []
  const d = weekStart.value
  const date = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
  return generateSlots(date, 7, currentTeacher.value.timezone, viewerTimezone.value, currentTeacher.value.default_lesson_minutes, availability.value, blocked.value, busySlots.value)
})
function tr(en: string, zh: string) { return language.value === 'en' ? en : zh }
function showToast(v: string) { toast.value = v; window.setTimeout(() => toast.value = '', 3000) }
function setError(e: unknown) { const code = typeof e === 'object' && e !== null && 'context' in e ? String((e as { context?: { error?: string } }).context?.error || '') : ''; errorMessage.value = ({ unauthorized: tr('Your session has expired. Please sign in again.', '登录已过期，请重新登录。'), admin_only: tr('Administrator access is required.', '需要管理员权限。'), teacher_only: tr('Teacher access is required.', '需要老师权限。'), student_only: tr('Student access is required.', '需要学生权限。'), slot_unavailable: tr('This time is no longer available.', '该时间已不可预约。') }[code] || (e instanceof Error ? e.message : copy.value.authGeneric)) }
function toggleLanguage() { language.value = language.value === 'en' ? 'zh' : 'en'; localStorage.setItem('edubook-language', language.value) }
async function loadData() {
  if (!profile.value) return; loading.value = true; errorMessage.value = ''
  try {
    const t = await supabase.from('profiles').select('*').eq('role','TEACHER').order('display_name'); if (t.error) throw t.error; teachers.value = t.data as Profile[]; if (!selectedTeacherId.value && teachers.value[0]) selectedTeacherId.value = teachers.value[0].id
    const b = await supabase.from('bookings').select('*').or(`student_id.eq.${profile.value.id},teacher_id.eq.${profile.value.id}`); if (b.error) throw b.error; bookings.value = b.data as Booking[]
    if (profile.value.role === 'ADMIN') { const u = await supabase.from('profiles').select('*').order('created_at',{ascending:false}); if (u.error) throw u.error; users.value = u.data as Profile[] }
    const teacherId = profile.value.role === 'TEACHER' ? profile.value.id : selectedTeacherId.value
    if (teacherId) {
      const [a, p] = await Promise.all([supabase.from('teacher_availability').select('*').eq('teacher_id',teacherId).order('weekday'), supabase.from('teacher_blocked_periods').select('*').eq('teacher_id',teacherId).order('start_at_utc')]); if (a.error) throw a.error; if (p.error) throw p.error; availability.value = a.data as Availability[]; blocked.value = p.data as BlockedPeriod[]
      const from = new Date(weekStart.value.getFullYear(),weekStart.value.getMonth(),weekStart.value.getDate()).toISOString(); const until = new Date(new Date(from).getTime()+604800000).toISOString()
      const busyResult = await supabase.functions.invoke('teacher-busy-slots',{body:{teacherId,from,until}}); if (busyResult.error) throw busyResult.error; busySlots.value = (busyResult.data?.slots || []) as BusySlot[]
    }
  } catch (e) { setError(e) } finally { loading.value = false }
}
async function signIn() { busy.value=true; try { if (!supabaseConfigured) throw new Error(copy.value.setupMissing); const r=await supabase.auth.signInWithPassword({email:`${auth.value.username.trim().toLowerCase()}@accounts.edubook.internal`,password:auth.value.password}); if(r.error) throw r.error } catch(e){setError(e)} finally{busy.value=false} }
async function restore(id:string) { const r=await supabase.from('profiles').select('*').eq('id',id).maybeSingle(); if(r.error || !r.data){setError(r.error||new Error('profile_not_found'));return}; profile.value=r.data as Profile; await loadData() }
async function createUser() { busy.value=true; try { const r=await supabase.functions.invoke('admin-create-user',{body:adminForm.value}); if(r.error) throw r.error; adminForm.value={username:'',password:'',displayName:'',role:'STUDENT',timezone:detectedTimezone};showToast(tr('Account created.','账户已创建。'));await loadData() }catch(e){setError(e)}finally{busy.value=false} }
async function addAvailability(){if(!profile.value)return; try{const r=await supabase.from('teacher_availability').insert({teacher_id:profile.value.id,weekday:newRule.value.weekday,local_start_time:newRule.value.start,local_end_time:newRule.value.end});if(r.error)throw r.error;await loadData()}catch(e){setError(e)}}
async function removeAvailability(id:string){const r=await supabase.from('teacher_availability').delete().eq('id',id);if(r.error)setError(r.error);else await loadData()}
async function addBlocked(){if(!profile.value||!blockedForm.value.start||!blockedForm.value.end)return;try{const r=await supabase.from('teacher_blocked_periods').insert({teacher_id:profile.value.id,start_at_utc:new Date(blockedForm.value.start).toISOString(),end_at_utc:new Date(blockedForm.value.end).toISOString(),reason:blockedForm.value.reason||null});if(r.error)throw r.error;blockedForm.value={start:'',end:'',reason:''};await loadData()}catch(e){setError(e)}}
async function saveMinutes(){if(!profile.value)return;const r=await supabase.rpc('update_my_profile',{p_display_name:profile.value.display_name,p_timezone:profile.value.timezone,p_default_lesson_minutes:profile.value.default_lesson_minutes});if(r.error)setError(r.error);else{profile.value=r.data as Profile;showToast(tr('Lesson duration saved.','课程时长已保存。'))}}
async function book(){if(!selectedSlot.value||!currentTeacher.value)return;busy.value=true;try{const r=await supabase.functions.invoke('create-booking',{body:{teacherId:currentTeacher.value.id,startAtUtc:selectedSlot.value.startAtUtc,endAtUtc:selectedSlot.value.endAtUtc}});if(r.error)throw r.error;selectedSlot.value=null;showToast(tr('Booking request submitted.','预约申请已提交。'));await loadData()}catch(e){setError(e)}finally{busy.value=false}}
async function action(id:string,a:'confirm'|'reject'|'cancel'){try{const r=await supabase.functions.invoke('booking-action',{body:{bookingId:id,action:a}});if(r.error)throw r.error;showToast(tr('Booking updated.','预约已更新。'));await loadData()}catch(e){setError(e)}}
function selectTeacher(id:string){selectedTeacherId.value=id;selectedSlot.value=null;loadData()} function shift(days:number){weekStart.value=new Date(weekStart.value.getTime()+days*86400000);loadData()}
onMounted(async()=>{const r=await supabase.auth.getSession();session.value=r.data.session?{user:{id:r.data.session.user.id}}:null;if(session.value)await restore(session.value.user.id);supabase.auth.onAuthStateChange(async(_e,next)=>{session.value=next?{user:{id:next.user.id}}:null;if(next)await restore(next.user.id)})})
</script>
<template>
  <main v-if="!session || !profile" class="auth-shell"><section class="auth-card"><div class="auth-top"><div class="brand"><span class="brand-mark">E</span><span>EduBook</span></div><button class="language-button" @click="toggleLanguage">{{copy.language}}</button></div><span class="section-kicker">{{copy.workspace}}</span><h1>{{copy.loginTitle}}</h1><p class="auth-intro">{{copy.intro}}</p><p v-if="!supabaseConfigured" class="notice">Supabase is not configured for this deployment yet.</p><form @submit.prevent="signIn"><label>{{tr('Username','账号名')}}<input v-model="auth.username" autocomplete="username" required /></label><label>{{copy.password}}<input v-model="auth.password" type="password" autocomplete="current-password" minlength="8" required /></label><p v-if="errorMessage" class="form-error">{{errorMessage}}</p><button class="primary-button full" :disabled="busy||!supabaseConfigured">{{busy?copy.processing:copy.login}}</button></form><p class="auth-note">{{tr('Accounts are created by an administrator.','账户由管理员创建。')}}</p></section></main>
  <div v-else class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">E</span><span>EduBook</span></div><nav class="nav-list"><button class="nav-item" :class="{active:activeNav==='book'}" @click="activeNav='book'">{{copy.booking}}</button><button class="nav-item" :class="{active:activeNav==='history'}" @click="activeNav='history'">{{copy.myBookings}}</button><button v-if="profile.role==='ADMIN'" class="nav-item" :class="{active:activeNav==='admin'}" @click="activeNav='admin'">{{tr('User management','用户管理')}}</button><button v-if="profile.role==='TEACHER'" class="nav-item" :class="{active:activeNav==='requests'}" @click="activeNav='requests'">{{copy.manage}}</button><button v-if="profile.role==='TEACHER'" class="nav-item" :class="{active:activeNav==='schedule'}" @click="activeNav='schedule'">{{copy.schedule}}</button></nav><div class="profile-mini"><div class="avatar avatar-user">{{profile.display_name.slice(0,2)}}</div><div><strong>{{profile.display_name}}</strong><small>{{profile.timezone}}</small></div><button class="signout" @click="async()=>{await supabase.auth.signOut();session=null;profile=null}">{{copy.signOut}}</button></div></aside>
  <section class="main-content"><header class="topbar"><div><p class="eyebrow">{{new Intl.DateTimeFormat(language==='en'?'en-US':'zh-CN',{dateStyle:'full',timeZone:viewerTimezone}).format(new Date())}}</p><h1>{{activeNav==='admin'?tr('Account management','账户管理'):copy.findLesson}}</h1></div><button class="language-button" @click="toggleLanguage">{{copy.language}}</button></header><p v-if="errorMessage" class="notice error-state">{{errorMessage}} <button class="text-button" @click="loadData">{{copy.retry}}</button></p>
  <section v-if="activeNav==='admin'" class="dashboard-panel"><div class="panel wide"><div class="panel-head"><div><strong>{{tr('Create account','创建账户')}}</strong><span>{{tr('Teacher or student, no email required','老师或学生，无需邮箱')}}</span></div></div><form class="inline-form" @submit.prevent="createUser"><input v-model="adminForm.username" name="username" required pattern="[A-Za-z0-9_.-]{3,40}" :placeholder="tr('Username','账号名')" /><input v-model="adminForm.password" type="password" minlength="8" required :placeholder="tr('Temporary password','临时密码')" /><input v-model="adminForm.displayName" required :placeholder="tr('Display name','显示名称')" /><select v-model="adminForm.role"><option value="STUDENT">{{copy.student}}</option><option value="TEACHER">{{copy.teacher}}</option></select><select v-model="adminForm.timezone"><option v-for="z in timezoneOptions" :key="z">{{z}}</option></select><button class="primary-button" :disabled="busy">{{tr('Create account','创建账户')}}</button></form></div><div class="panel wide"><div v-for="user in users" :key="user.id" class="booking-row"><div class="avatar avatar-user">{{user.display_name.slice(0,2)}}</div><div class="booking-name"><strong>{{user.display_name}}</strong><span>{{user.username}}</span></div><span class="status-pill confirmed">{{user.role}}</span><small>{{user.timezone}}</small></div></div></section>
  <section v-else-if="activeNav==='schedule'" class="teacher-panels"><div class="panel wide"><div v-for="r in availability" :key="r.id" class="availability-row"><span>{{r.weekday}}</span><strong>{{r.local_start_time.slice(0,5)}} – {{r.local_end_time.slice(0,5)}}</strong><button class="text-button" @click="removeAvailability(r.id)">{{copy.remove}}</button></div><form class="inline-form" @submit.prevent="addAvailability"><select v-model="newRule.weekday"><option v-for="d in 7" :key="d" :value="d-1">{{d-1}}</option></select><input v-model="newRule.start" type="time" required/><input v-model="newRule.end" type="time" required/><button class="primary-button">{{copy.add}}</button></form></div><div class="panel"><label>{{copy.minutes}}<input v-model.number="profile.default_lesson_minutes" type="number" min="5" max="240" step="5"/></label><button class="outline-button" @click="saveMinutes">{{copy.save}}</button></div><div class="panel wide"><div v-for="p in blocked" :key="p.id" class="availability-row blocked"><strong>{{formatViewerTime(p.start_at_utc,profile.timezone)}}</strong><small>{{p.reason}}</small></div><form class="inline-form" @submit.prevent="addBlocked"><input v-model="blockedForm.start" type="datetime-local" required/><input v-model="blockedForm.end" type="datetime-local" required/><input v-model="blockedForm.reason" :placeholder="tr('Reason (optional)','原因（可选）')"/><button class="primary-button">{{copy.add}}</button></form></div></section>
  <section v-else-if="activeNav==='requests'" class="dashboard-panel"><div class="panel wide"><div v-for="b in teacherBookings" :key="b.id" class="booking-row"><div class="booking-time">{{formatViewerTime(b.start_at_utc,profile.timezone)}}</div><strong>{{b.status}}</strong><div class="row-actions"><button v-if="b.status==='PENDING'" class="mini-button" @click="action(b.id,'confirm')">{{copy.confirm}}</button><button v-if="b.status==='PENDING'" class="mini-button ghost" @click="action(b.id,'reject')">{{copy.reject}}</button><button v-if="b.status==='CONFIRMED'" class="mini-button ghost" @click="action(b.id,'cancel')">{{copy.cancel}}</button></div></div><p v-if="!teacherBookings.length">{{tr('No booking requests.','暂无预约申请。')}}</p></div></section>
  <section v-else-if="activeNav==='history'" class="dashboard-panel"><div class="panel wide"><div v-for="b in studentBookings" :key="b.id" class="booking-row"><div class="booking-time">{{formatViewerTime(b.start_at_utc,viewerTimezone)}}</div><strong>{{b.status}}</strong></div><p v-if="!studentBookings.length">{{copy.noBookings}}</p></div></section>
  <section v-else class="content-grid"><div class="primary-column"><div class="teacher-list"><button v-for="t in teachers" :key="t.id" class="teacher-card" :class="{chosen:currentTeacher?.id===t.id}" @click="selectTeacher(t.id)"><span class="avatar avatar-coral">{{t.display_name.slice(0,2)}}</span><span class="teacher-info"><strong>{{t.display_name}}</strong><span>{{t.timezone}}</span><small>{{t.default_lesson_minutes}} min</small></span></button><p v-if="!teachers.length">{{copy.noTeachers}}</p></div><div class="calendar-nav"><button @click="shift(-7)">‹</button><span>{{copy.shownIn}}: {{viewerTimezone}}</span><button @click="shift(7)">›</button></div><div class="slot-list"><button v-for="s in slots" :key="s.startAtUtc" class="slot-item" :class="{unavailable:!s.available,selected:selectedSlot?.startAtUtc===s.startAtUtc}" :disabled="!s.available" @click="selectedSlot=s"><span>{{s.viewerStart}}</span><strong>{{s.available?'Available':'Booked'}}</strong></button><p v-if="loading">{{copy.processing}}</p><p v-if="!loading&&!slots.length">{{copy.noSlots}}</p></div></div><aside class="booking-summary"><h3>{{selectedSlot?tr('Confirm this lesson','确认预约'):copy.selectTime}}</h3><p v-if="selectedSlot">{{selectedSlot.viewerStart}} – {{selectedSlot.viewerEnd}}</p><button class="primary-button" :disabled="!selectedSlot||busy" @click="book">{{copy.submit}}</button></aside></section></section></div><div v-if="toast" class="toast" role="status">{{toast}}</div>
</template>
